### ISSUE TITLE
*solicitud* agregar de manera manual los animes

### ISSUE THREAD

**Issue by lokillo999** [jordyamc/UKIKU#19]
Agregar la posibilidad de agregar los animes de manera externa (bajarlos en la PC y pasarlos al teléfono) en caso de que la app tenga errores en el servidor

**Comment by kit5une** [comment]
Para eso puedes usar la opción de importar que ya esta implementada

**Comment by lokillo999** [comment]
Lo intente pero no lo detecta la app
![Screenshot_20200501-183443_MiXplorer](https://user-images.githubusercontent.com/19214569/80850705-8775d800-8bda-11ea-85f7-c445dc24a3fb.jpg)
![Screenshot_20200501-183450_MiXplorer](https://user-images.githubusercontent.com/19214569/80850714-90ff4000-8bda-11ea-82bf-31dfc84d3dbd.jpg)
![Screenshot_20200501-183507_UKIKU](https://user-images.githubusercontent.com/19214569/80850720-95c3f400-8bda-11ea-8f6f-a0ce1d4c01ed.jpg)

**Comment by kit5une** [comment]
Tienes que ir a la pantalla de episodios del anime y importar uno por uno 
![photo_2020-05-01_19-40-50](https://user-images.githubusercontent.com/40864150/80850833-b3498b80-8be3-11ea-9d41-31e42b8cb3c4.jpg)

**Comment by lokillo999** [comment]
gracias no conocia la opcion de hacer eso jaja bueno como esta "resuelto" voy a cerrar esto
