### ISSUE TITLE
data real time sinc

### ISSUE THREAD

**Issue by Kronos2308** [jordyamc/UKIKU#26]
Some time you have more that one device 
In my case I have 3 
And would be nice to have the option to sinc that devices in real time 

I know exist a sinc system but a switch or something to sinc the data in the moment is updated in any place 

I mean if you see a video in one device that info is reflected in te other two at the same time

**Comment by jordyamc** [comment]
That feature is enabled when using Firestore as backup

**Comment by Kronos2308** [comment]
But fire tv stick not allow firestore

**Comment by ToastcodeDev** [comment]
Diría que un botón también ayudaria, ya que en ocasiones vemos un anime y queremos que esté se guarde en la base de datos pero la aplicación dijo que anteriormente ya fue sincronizado así que tenemos que reiniciarla para que está pueda guardarlo.
