### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by johnx32** [jordyamc/UKIKU#5]
Me sale error al compilar el proyecto

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE FAILED in 2s
Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

**Comment by jordyamc** [comment]
Debes sustituir los campos privados en el build.gradle

**Comment by johnx32** [comment]
Cuales campos privados ? el buildTypes ??
lo tengo asi:

`buildTypes {
        def APPCOINS_IAB_KEY = "APPCOINS_IAB_KEY"
        def APPCOINS_IAB_UPDATE_ACTION = "APPCOINS_IAB_UPDATE_ACTION"
        def APPCOINS_DEV_IAB_BIND_ACTION = "APPCOINS_DEV_IAB_BIND_ACTION"
        def APPCOINS_DEV_IAB_BIND_PACKAGE = "APPCOINS_DEV_IAB_BIND_PACKAGE"
        def APPCOINS_ADDRESS = "APPCOINS_ADDRESS"
        def DROPBOX_TOKEN = "DROPBOX_TOKEN"
        def EASTER_SEARCH = "EASTER_SEARCH"
        def APPCOINS_IAB_BIND_ACTION = "APPCOINS_IAB_BIND_ACTION"
        def APPCOINS_IAB_BIND_PACKAGE = "APPCOINS_IAB_BIND_PACKAGE"

        debug {
            buildConfigField "String", "IAB_KEY",
                    "\"" + APPCOINS_IAB_KEY + "\""
            buildConfigField "String", "IAB_UPDATE_ACTION",
                    "\"" + APPCOINS_IAB_UPDATE_ACTION + "\""
            buildConfigField "String", "IAB_BIND_ACTION",
                    "\"" + APPCOINS_DEV_IAB_BIND_ACTION + "\""
            buildConfigField "String", "IAB_BIND_PACKAGE",
                    "\"" + APPCOINS_DEV_IAB_BIND_PACKAGE + "\""
            buildConfigField "String", "APPCOINS_ADDRESS",
                    "\"" + APPCOINS_ADDRESS + "\""
            buildConfigField "String", "DROPBOX_TOKEN",
                    "\"" + DROPBOX_TOKEN + "\""
            manifestPlaceholders = [iabPermission: "com.appcoins.dev.BILLING"]
            buildConfigField "String", "EASTER_SEARCH",
                    "\"" + EASTER_SEARCH + "\""
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-android.txt'
            buildConfigField "String", "IAB_KEY",
                    "\"" + APPCOINS_IAB_KEY + "\""
            buildConfigField "String", "IAB_UPDATE_ACTION",
                    "\"" + APPCOINS_IAB_UPDATE_ACTION + "\""
            buildConfigField "String", "IAB_BIND_ACTION",
                    "\"" + APPCOINS_IAB_BIND_ACTION + "\""
            buildConfigField "String", "IAB_BIND_PACKAGE",
                    "\"" + APPCOINS_IAB_BIND_PACKAGE + "\""
            buildConfigField "String", "APPCOINS_ADDRESS",
                    "\"" + APPCOINS_ADDRESS + "\""
            buildConfigField "String", "DROPBOX_TOKEN",
                    "\"" + DROPBOX_TOKEN + "\""
            buildConfigField "String", "EASTER_SEARCH",
                    "\"" + EASTER_SEARCH + "\""
        }
        tv {
            initWith release
            applicationIdSuffix ".tv"
        }
        playstore {
            initWith release
        }
    }`

**Comment by johnx32** [comment]
tengo la versión 3.1.2

**Comment by jordyamc** [comment]
Tal vez sea eso, yo uso la 3.5 Canary 1

**Comment by johnx32** [comment]
ok, mi Internet es lento no se cuando lo actualizare para ver eso, de momento cerrare el issue, si hay alguna novedad vuelvo

**Comment by blackhole-chan** [comment]
> Debes sustituir los campos privados en el build.gradle

Donde puedo conseguir los tokens para sustituirlos?
